name: Build BasicOS

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image
      run: docker build -t basicos-dev .
      
    - name: Build BasicOS
      run: docker run --rm -v ${{ github.workspace }}:/workspace basicos-dev make all
      
    - name: Test OS binary exists
      run: |
        if [ ! -f build/basicos.bin ]; then
          echo "Error: BasicOS binary not found!"
          exit 1
        fi
        echo "BasicOS binary size: $(stat -c%s build/basicos.bin) bytes"
        
    - name: Upload BasicOS binary
      uses: actions/upload-artifact@v4
      with:
        name: basicos-binary
        path: build/basicos.bin
        retention-days: 30
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          build/*.bin
          build/*.o
        retention-days: 7
