name: Build BasicOS

on:
  workflow_dispatch:
    inputs:
      upload_artifacts:
        description: 'Upload build artifacts'
        required: false
        default: 'true'
        type: boolean
      retention_days:
        description: 'Artifact retention days'
        required: false
        default: '30'
        type: string
  pull_request:
    branches: [ master ]
    paths:
      - '**.c'
      - '**.h'
      - '**.asm'
      - 'Makefile'
      - 'link.ld'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image
      run: docker build -t basicos-dev .
      
    - name: Build BasicOS
      run: docker run --rm -v ${{ github.workspace }}:/workspace basicos-dev make all
      
    - name: Test OS binary exists
      run: |
        if [ ! -f build/basicos.bin ]; then
          echo "Error: BasicOS binary not found!"
          exit 1
        fi
        echo "BasicOS binary size: $(stat -c%s build/basicos.bin) bytes"
        
    - name: Upload BasicOS binary
      if: github.event_name == 'workflow_dispatch' && inputs.upload_artifacts == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: basicos-binary
        path: build/basicos.bin
        retention-days: ${{ inputs.retention_days || '30' }}
        
    - name: Upload build artifacts
      if: github.event_name == 'workflow_dispatch' && inputs.upload_artifacts == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          build/*.bin
          build/*.o
        retention-days: 7
