name: Test BasicOS

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 2 * * 1' 

jobs:
  test-build:
    runs-on: ubuntu-latest
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
        
    - name: Build and test
      run: |
        # Build Docker image
        docker build -t basicos-dev-test .
        
        # Test basic tools are available
        docker run --rm basicos-dev-test nasm --version
        docker run --rm basicos-dev-test gcc --version
        docker run --rm basicos-dev-test make --version
        
        # Build BasicOS with proper permissions
        docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace --user $(id -u):$(id -g) basicos-dev-test make all
        
        # Verify binary was created and has reasonable size
        if [ ! -f build_output/basicos.bin ]; then
          echo "Error: BasicOS binary not created"
          exit 1
        fi
        
        SIZE=$(stat -c%s build_output/basicos.bin)
        if [ $SIZE -lt 1024 ]; then
          echo "Error: Binary too small ($SIZE bytes)"
          exit 1
        fi
        
        if [ $SIZE -gt 1048576 ]; then
          echo "Warning: Binary quite large ($SIZE bytes)"
        fi
        
        echo "Build successful! Binary size: $SIZE bytes"

  test-components:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build Docker image
      run: docker build -t basicos-dev .
      
    - name: Test individual components
      run: |
        # Test bootloader compilation (output to /tmp inside container)
        docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace basicos-dev sh -c "nasm -f bin boot/boot.asm -o /tmp/test-boot.bin && echo 'Bootloader test: PASS'"
        
        # Test kernel compilation
        docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace basicos-dev sh -c "nasm -f elf32 kernel/kernel_entry.asm -o /tmp/test-kernel.o && echo 'Kernel ASM test: PASS'"
        
        # Test C compilation
        docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace basicos-dev sh -c "gcc -m32 -nostdlib -nostdinc -fno-builtin -fno-stack-protector -nostartfiles -nodefaultlibs -Wall -Wextra -Werror -Wno-main -fno-zero-initialized-in-bss -fno-pic -c -I. kernel/main.c -o /tmp/test-main.o && echo 'C compilation test: PASS'"
        
        # Test syntax only (no output files)
        docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace basicos-dev sh -c "nasm -f bin boot/boot.asm -o /dev/null && echo 'Bootloader syntax: PASS'"
        
        echo "All component tests passed!"

  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'ubuntu:22.04'
        format: 'sarif'
        output: 'trivy-results.sarif'
        
    - name: Upload Trivy scan results
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'
